# Generated by Django 3.0.6 on 2020-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideosDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video_img', models.ImageField(upload_to='')),
                ('views', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], default='하', max_length=5)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
