# Generated by Django 3.0.6 on 2020-05-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideosDB',
            fields=[
                ('video_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video_img', models.ImageField(upload_to='')),
                ('views', models.IntegerField(default=0)),
                ('level', models.CharField(max_length=5)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
