# Generated by Django 3.0.6 on 2020-05-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDB',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_birth', models.DateField()),
            ],
        ),
    ]
