# Generated by Django 3.0.6 on 2020-06-16 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Videos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdusDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_description', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_shared', models.CharField(choices=[('공유 안함', '공유 안함'), ('공유 함', '공유 함')], default='공유 안함', max_length=5)),
                ('edu_days', models.DateTimeField(auto_now_add=True)),
                ('recode_video', models.FileField(null=True, upload_to='edus/', verbose_name='')),
                ('score', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videos.VideosDB')),
            ],
        ),
    ]
