# Generated by Django 3.0.6 on 2020-05-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdusDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_days', models.DateTimeField(auto_now_add=True)),
                ('recode_video', models.FileField(upload_to='')),
                ('score', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.UsersDB')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videos.VideosDB')),
            ],
        ),
    ]
