# Generated by Django 3.0.6 on 2020-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdusDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_description', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_shared', models.CharField(choices=[('공유 안함', '공유 안함'), ('공유 함', '공유 함')], default='공유 안함', max_length=5)),
                ('edu_days', models.DateTimeField(auto_now_add=True)),
                ('recode_video', models.FileField(null=True, upload_to='edus/', verbose_name='')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
