# Generated by Django 3.0.6 on 2020-06-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Edus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edusdb',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edusdb',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videos.VideosDB'),
        ),
    ]
